In [1]:
import numpy as np                           #To find the range
ar1=np.arange(13)

In [ ]:
ar1
len(ar1)

In [11]:
reshaped_array=ar1.reshape(13,1)

In [12]:
reshaped_array


array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [3]:
np.eye(5)           #identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
np.eye(4,3)            # Used to define both user defined rows and columns
                       #syntax-->np.eye(3,4) , 3 rows and 4 columns

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [7]:
np.identity(5)                                   #rows and columns have to be same for identity matrix in this in-built function
                                                   # syntax -->np.identity(5)  , 5 rows and 5 columnsn

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
np.identity(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [14]:
ar2=np.arange(25)
ar2.shape

(25,)

(25,)

In [15]:
# To perform multi dimensional slicing
ar2=np.arange(25).reshape(5,5)

In [16]:
ar2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
ar2.shape       # Considered as a property


(5, 5)

In [18]:
# ar2[rows,columns,step]
# ar2[row_start:row_end,col_start,col_end,step]
ar2[0:3,1:4]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [22]:
ar2[4:5,3:5]

array([[23, 24]])

In [28]:
ar2[-3:-5]    # 5 is greater than 3 . So it shows empty list

array([], shape=(0, 5), dtype=int64)

In [51]:
np.sum(ar2,axis=0)   # To add based on column wise axis=0
ar2


[-5, -3]

In [ ]:
# Mean = average
# Median=center value
# Mode=Max no of repeated elements
# varience=Median /Total no of elements
# standard deviation=square root of varience

In [56]:
#linspace()
#It is used to print the evenly separated points between 2 range of values
np.linspace(1,5, dtype=int)         #linspace(start,end, no of values)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 5])

In [53]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [54]:
np.linspace(1,11,5)

array([ 1. ,  3.5,  6. ,  8.5, 11. ])

In [63]:
np.linspace(1,10,4, retstep=True)        # 1 to 10 numbers equally divided into 4 parts       #retstep returns the common difference of each number

(array([ 1.,  4.,  7., 10.]), 3.0)

In [59]:
#Random module
# To generate random num betweeen the range
# np.random.randint(start,end,no_of_values)
np.random.randint(40)

2

In [61]:
np.random.randint(20,30,3)          #3--> Randomly generated 3 numbers

array([20, 23, 23])

In [64]:
#rand() -->
# To get the randomly generated values from 0 to 1,based on uniform distribution
np.random.rand(5)


array([0.72881153, 0.11194589, 0.2831716 , 0.34000516, 0.85927232])

In [76]:
import numpy as np
np.random.rand(5,4)

array([[0.88201078, 0.7113291 , 0.5099015 , 0.44932704],
       [0.60814267, 0.49036729, 0.65689972, 0.55981139],
       [0.28817683, 0.96780687, 0.6581407 , 0.56632227],
       [0.06963154, 0.50216438, 0.86044514, 0.30338348],
       [0.96831281, 0.98468894, 0.5212186 , 0.54677217]])

In [77]:
#rand() -->
# To get the randomly generated values from 0 to 2 , based on normalised distribution
np.random.randn(5)

array([-0.43242341, -0.73462533, -0.70191807, -0.32505516,  0.33432336])

In [79]:
np.random.randn(5,4)

array([[ 0.33403168,  0.91883518, -0.51963305, -0.64614126],
       [ 1.14092179, -2.18755307, -1.16963339, -1.00733679],
       [ 0.78744657, -1.18345082,  0.59103479, -0.67702905],
       [-0.08389903,  0.00284317,  1.60186659, -2.23395102],
       [ 0.16509092, -0.13526317,  1.02960318, -0.19260263]])

In [90]:
l1=[56,89,90,67,45]
np1=np.array(l1)

In [91]:
print(np1.argmin())   # argmin-->to find the min values index position in an array


4


In [92]:
print(np1.argmax())    #argmax--> to find the max values index position in an array

2


In [93]:
np.sin(np1)

array([-0.521551  ,  0.86006941,  0.89399666, -0.85551998,  0.85090352])

In [94]:
np.cos(np1)

array([ 0.85322011,  0.51017704, -0.44807362, -0.5177698 ,  0.52532199])

In [96]:
np.tan(np1)


array([-0.61127369,  1.68582537, -1.99520041,  1.65231726,  1.61977519])

In [97]:
np.cos(np1)/np.sin(np1)

array([-1.63592842,  0.59318125, -0.50120278,  0.60521065,  0.61736962])

In [101]:
np.sin(np1)/np.cos(np1)

array([-0.61127369,  1.68582537, -1.99520041,  1.65231726,  1.61977519])

In [98]:
1/np.cos(np1)

array([ 1.17203051,  1.96010387, -2.23177613, -1.93136023,  1.90359441])

In [99]:
1/np.sin(np1)

array([-1.91735803,  1.16269686,  1.11857241, -1.16887977,  1.17522136])

In [100]:
1/np.tan(np1)

array([-1.63592842,  0.59318125, -0.50120278,  0.60521065,  0.61736962])

In [107]:
np2=np.array([1,2,3])
np3=np.arrayS([4,5,6])
np4=np2*np3
sum(np4)

32

In [ ]:
np.dot(np2,np3)        # To add

In [ ]:
fname=np.array(["sid","fn1","fn2"])
lname=np.array(['T',"ln1","ln2"])
result=concatenate(fname,lname)


In [117]:
np2=np.array([1,2,3,8,3,5,7])
np2=np.array([7,8,9])
len1=len(np2)
len2=len(np3)
diff=abs(len1-len2)
for value in range(diff):
  np3=np.append(np3,1)
  np.sum((np2*np3))


In [114]:
np1=np.array([1,34,56,78,np.nan,np.nan])
#to print nan values
np1[np.isnan(np1)]

array([nan, nan])

In [115]:
#to eliminate nan values
np1[~np.isnan(np1)]

array([ 1., 34., 56., 78.])

In [ ]:
np.dot(np2,np3)

In [3]:
#Pandas
import pandas as pd
import numpy as np
#Panda is defines as open-source library that provides high-performance data manipulation in python
#Data analysis requires lot of processing such as restructuring, cleaning, mergin, manipulating etc.. We prefer pandas to perform above functionalities because it is fast,
#similar than other tools.
#Pandas is built on Numpy, Numpy is required for operating pandas

#Pandas Series
#Pandas series is a data structure with one dimensional labelled array
#It is a primary building block of DataFrame making it's rows and columns

labels=['a','b','c']
my_data=[10,20,30]
arr=np.array(my_data)
d={"a":100, "b":200, "c":300}

In [4]:
# Series(data=None, index=None, dtype=None, name=None, copy=True or False)
# Ex:1
import pandas as pd
pd.Series(my_data)


0    10
1    20
2    30
dtype: int64

In [5]:
type(pd.Series(my_data))

pandas.core.series.Series

In [10]:
# Series with labels
#pd.Series(data=my_data,index=labels)
            # or
pd.Series(my_data, labels)

a    10
b    20
c    30
dtype: int64

In [8]:
pd.Series(data=[print, len, sum])

0    <built-in function print>
1      <built-in function len>
2      <built-in function sum>
dtype: object

In [12]:
ser1=pd.Series([1,2,3,4,5] ,["USA" ,"India", "Canada", "UK", "Egypt"])

In [13]:
ser1

USA       1
India     2
Canada    3
UK        4
Egypt     5
dtype: int64

In [15]:
ser1["USA"]

1

In [16]:
# Access values using index
ser1[0:3]

USA       1
India     2
Canada    3
dtype: int64

In [18]:
ser2=pd.Series([5,6,7,8],["USA", "Brazil", "Canada", "UK"])
ser1+ser2

Brazil     NaN
Canada    10.0
Egypt      NaN
India      NaN
UK        12.0
USA        6.0
dtype: float64

In [19]:
# To create a new data in series
ser2

USA       5
Brazil    6
Canada    7
UK        8
dtype: int64

In [21]:
ser2["China"]="Duplicate"       # To add
ser2


USA               5
Brazil            6
Canada            7
UK                8
China     Duplicate
dtype: object

In [22]:
ser2.drop("USA")   # To delete

Brazil            6
Canada            7
UK                8
China     Duplicate
dtype: object

In [24]:
#DataFrame
#pd.DataFrame(datas, Row_label, column_label)

df=pd.DataFrame(np.random.randn(5,4))
df

0         1         2         3
0 -0.114560  0.759514 -0.445988  0.002538
1 -0.346468  0.284572  1.218468 -2.679395
2  2.362279  0.960561 -0.331808  1.208070
3 -0.190359 -1.037602 -1.108132  1.392222
4  0.170429 -0.919397 -0.506049 -0.660114

In [26]:
# To convert Dictionary to dataFrame
d={"col1":[1,2],"col2":[3,4],"col3":[5,6]}
d


{'col1': [1, 2], 'col2': [3, 4], 'col3': [5, 6]}

In [28]:
df=pd.DataFrame(data=d)
df

col1  col2  col3
0     1     3     5
1     2     4     6

In [29]:
df=pd.DataFrame(d,["row1","row2"])
df

col1  col2  col3
row1     1     3     5
row2     2     4     6

In [31]:
df.index


Index(['row1', 'row2'], dtype='object')

In [33]:
np.random.randn(5,4), ['A','B','C','D' ,'E'],['W', 'X','Y','Z']

(array([[ 1.62868052,  0.7398833 , -1.19562818,  0.68711602],
        [ 0.03468423, -0.07684433, -1.88780334,  1.00661375],
        [ 0.19054961,  0.86594082, -0.8755818 , -0.21608198],
        [-0.80774416,  0.51417142,  1.3895754 , -0.04063332],
        [-0.74632675,  0.1838225 ,  0.66261956, -0.6741238 ]]),
 ['A', 'B', 'C', 'D', 'E'],
 ['W', 'X', 'Y', 'Z'])

In [32]:
df.T

row1  row2
col1     1     2
col2     3     4
col3     5     6

In [34]:
df.index

Index(['row1', 'row2'], dtype='object')

In [35]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [36]:
type(df)

pandas.core.frame.DataFrame

In [37]:
df.dtypes

col1    int64
col2    int64
col3    int64
dtype: object

In [38]:
df.info()               # To find information about DataFrame

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, row1 to row2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    2 non-null      int64
 1   col2    2 non-null      int64
 2   col3    2 non-null      int64
dtypes: int64(3)
memory usage: 172.0+ bytes


In [39]:
df.values      # To get values in array form

array([[1, 3, 5],
       [2, 4, 6]])

In [40]:
df.axes

[Index(['row1', 'row2'], dtype='object'),
 Index(['col1', 'col2', 'col3'], dtype='object')]

In [41]:
df.ndim

2

In [42]:
df.size

6

In [55]:
df["W"]

KeyError: 'W'

In [ ]:
type(df["W"])

In [ ]:
df[['','x','y']]

In [ ]:
df['new']=df['w']+df['y']

In [54]:
df.drop('new',axis=1,inplace=True)

KeyError: "['new'] not found in axis"